### PR TITLE
chore: bump version

### PR DESCRIPTION
**Pull request by hiwllc**
[skip ci]

### CODE REVIEW

**Comment by Philzen** [comment]
I'm so sorry, but just trying out the v2.8.0 release in our project i'm getting:

```shell
web | Failed to resolve entry for package "@uselessdev/datepicker". The package may have incorrect main/module/exports specified in its package.json.
web | 12:22:51 AM [vite] Internal server error: Failed to resolve entry for package "@uselessdev/datepicker". The package may have incorrect main/module/exports specified in its package.json.
web |   Plugin: vite:import-analysis
```

Using `"@uselessdev/datepicker": "https://github.com/Philzen/datepicker.git#commit=097e011ed9df0febb2f219ea8c18f8b5d303c143",` in the project's `package.json` works fine though (at least locally, on CI currently poses a challenge [due to a yarn bug](https://github.com/yarnpkg/berry/issues/1142#issuecomment-2261524260) i'm still trying to wrap my head around, but that should be unrelated to the problem at hand).

**Comment by Philzen** [comment]
@uselessdev just `rm -rf`ed the node__modules folder, did a clean install and found that the 2.8.0 release does not include a `dist/`-folder (and furthermore does not seem to include the changes from #84).

grafik

**Comment by uselessdev** [comment]
oh I probaly forget something, just a moment

**Comment by uselessdev** [comment]
@Philzen can you try with v2.8.1 and let me know if it works

**Comment by Philzen** [comment]
> @Philzen can you try with v2.8.1 and let me know if it works

Happy to report v2.8.1 is working fine and includes the updated `package.json`. Many thanks again.

**Comment by Philzen** [comment]
I've realized the [Releases page](https://github.com/uselessdev/datepicker/releases) (nor Tags) does not show 2.8.1 yet. In order to avoid confusion (and especially not have anybody accidentally trying to install the broken 2.8.0) i feel it may be vital to add it there.

Feeling a bit sorry for having caused all this late night kerfuffle on your side with this considerably non-critical fix – however on the upside there's one less `yarn install` warning now when using the component… and we've killed 50 % of the issues in this repo tonight :laughing:

**Comment by hiwllc** [comment]
ah yes, I just published the version on npm before the release in github, it's updated now 😊

**Pull request merged**
