### PR TITLE
Date library agnostic

### PR DESCRIPTION
**Pull request by AleksandrZhukov**
@uselessdev Firstly would like to say thanks for this library, it is amazing ❤️ 

I've prepared a new breaking changes feature - ability to change date library
I'm personally a fan of [Dayjs](https://github.com/iamkun/dayjs) and it is not super great to have two date libraries on project just because of Calendar component. So I decided add possibility to change date lib by selecting proper adapter. For now I've added adapters for date-fns and Dayjs, but it should be super simple too add more, if needed :wink:

Also I tried significantly improve typings of the Calendar, eg it is not possible to add `singleDateSelection` prop for DateRange calendar, or add `weekDateSelection` and `singleDateSelection` at the same time

Also it may help to save some Kb by switching to another adapter, in my case it helped me to save ~70kb gzip from bundle of my project

I will mark this PR as draft, cause it is definitely not ready to be merged
Feel free to leave comments and I'm open for discussion

### CODE REVIEW

**Comment by uselessdev** [comment]
Hi @AleksandrZhukov I really appreciate the effort on this PR and I think it make a lot of sense to be agnostic to date libraries, I have take a look at the code and have some things to point

first, I have planned a new release for this, but since I'm very busy (work, family and college stuffs) I don't have enough time to dedicate to this project 😭 

I think your changes here is a good fit to the next version ([I was doing something here](https://github.com/uselessdev/datepicker/blob/next/stories/calendar.stories.tsx)) the main ideia is split the project in UI (components) and logic (date handlers), maybe we can movo to a monorepo and split these in packages like this datepicker-headless, datepicker-date-fns, datepicker-dayjs (maybe we can give them better names)

Now, about the code, I still don't look deeply at the changes, but two things 

1. We should avoid use providers outside the library `CalendarAdapterProvider` (I don't know how to solve this, but I believe that can be easier with changes in next branch)

2. This is just a personal preference about types, I think we don't need to use prefixes like `TSomeType` just use `SomeType`

I'll make some time to look in the code asap, thanks again @AleksandrZhukov 😊

**Comment by AleksandrZhukov** [comment]
1 - I took the idea from MUI - https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns
2 - yeah, for most cases I used for `TDate` type, because `Date` is already used for native JS type, we can replace it with any other name, if you prefer

**Comment by uselessdev** [comment]
> 1 - I took the idea from MUI - https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns

Interesting, I think we can make this more 'generic' instead of have an internal adapter maybe user can provide it by their own 🤔 (if they know the api) this is why I suggest we change the target from `main` to `next` I believe it's easier to handle it in another way, what do you think?

**Comment by AleksandrZhukov** [comment]
Do you want some how to use MUI adapters?

**Comment by AleksandrZhukov** [comment]
I've checked next branch, file separation - is great, but I'm not sure I fully understand the idea of `useCalendar`, seems it is great only for storybook stories, cause for most applications it is important to have `value` and `onChange` handler to be able to use calendar in forms or any other user interfaces

**Comment by uselessdev** [comment]
> Do you want some how to use MUI adapters?

not exactly, (I don't use MUI so I don't know how it is 😬 )

**Comment by uselessdev** [comment]
> I've checked next branch, file separation - is great, but I'm not sure I fully understand the idea of `useCalendar` hook, seems it is great only for storybook stories, cause for most applications it is important to have `value` and `onChange` handler to be able to use calendar in forms or any other user interfaces

Yes I agree, the stories is missing examples to how to use with forms, I think I'll provide this soon, but it's possible 😊

**Comment by AleksandrZhukov** [comment]
Also seems `useCalendar` has some internal stuff, like generating the list of days for calendar view, that's mean user have to use that hook to make `Calendar` component to work. which is not super great, I think it should be additional feature if someone want it

**Comment by AleksandrZhukov** [comment]
If you want, I can apple similar folder/file splitting to my branch, it will definitely improve code readability

**Comment by uselessdev** [comment]
Hi @AleksandrZhukov sorry for the late reply, I'll take some time to think about how to implement adapters in the next version, for now, I'll close this PR

**Comment by AleksandrZhukov** [comment]
Up to you

**Pull request closed without merging**
